apiVersion: v1
name: api-spec-app
appVersion: 0.0.1
description: Serves the ReDoc container with the documentation of the Giant Swarm Rest API.
home: https://github.com/giantswarm/api-spec
version: "[[.Version]]"
annotations:
  application.giantswarm.io/team: honeybadger
